# Codemagic build configuration for iOS
workflows:
  ios-development:
    name: iOS Development Build
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.indigi.indigiAttendanceApp"
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Update Bundle Identifier
        script: |
          echo "Updating bundle identifier to $BUNDLE_ID"
          cd ios
          sed -i.bak "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" Runner.xcodeproj/project.pbxproj
          
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install

      - name: Build iOS without signing
        script: |
          flutter build ios --no-codesign --debug

    artifacts:
      - build/ios/**/*.app
      - build/ios/ipa/*.ipa

  ios-release:
    name: iOS Release & Upload to App Store
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials # Ensure you create this variable group in Codemagic UI if using env vars, or rely on Automatic Code Signing integration
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.indigi.indigiAttendanceApp"
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Update Bundle Identifier
        script: |
          echo "Updating bundle identifier to $BUNDLE_ID"
          cd ios
          sed -i.bak "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" Runner.xcodeproj/project.pbxproj

      - name: Set up keychain and fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install

      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - *.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration # Uses the API key configured in Codemagic UI (Distribution > iOS code signing)
        submit_to_testflight: true
