import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:upgrader/upgrader.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:indigi_attendance/controllers/auth_controller.dart';
import 'package:indigi_attendance/controllers/attendance_controller.dart';
import 'package:indigi_attendance/controllers/leave_controller.dart';
import 'package:indigi_attendance/controllers/client_visit_controller.dart';
import 'package:indigi_attendance/views/login_screen.dart';
import 'package:indigi_attendance/views/dashboard_screen.dart';
import 'package:indigi_attendance/firebase_options.dart';
import 'package:indigi_attendance/theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with options generated by FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => AuthController()),
        ChangeNotifierProvider(create: (context) => AttendanceController()),
        ChangeNotifierProvider(create: (context) => LeaveController()),
        ChangeNotifierProvider(create: (context) => ClientVisitController()),
      ],
      child: MaterialApp(
        title: 'Indigi Attendance',
        theme: AppTheme.themeData,
        home: UpgradeAlert(
          upgrader: Upgrader(
            durationUntilAlertAgain: Duration.zero,
          ),
          showIgnore: false,
          showLater: false,
          shouldPopScope: () => false,
          child: const AppLoader(),
        ),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}

class AppLoader extends StatelessWidget {
  const AppLoader({super.key});

  @override
  Widget build(BuildContext context) {
    final authController = Provider.of<AuthController>(context);

    // Show loading screen while checking auto-login
    if (authController.isCheckingAutoLogin) {
      return Scaffold(
        backgroundColor: AppTheme.surface,
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: AppTheme.accentLight,
                  borderRadius: AppTheme.radiusXXL,
                ),
                child: SizedBox(
                  height: 80,
                  width: 80,
                  child: Image.asset(
                    'assets/logo.png',
                    fit: BoxFit.contain,
                    errorBuilder: (context, error, stackTrace) {
                      return const Icon(
                        Icons.business_center_rounded,
                        size: 48,
                        color: AppTheme.accent,
                      );
                    },
                  ),
                ),
              ),
              const SizedBox(height: 32),
              const Text(
                'Indigi',
                style: TextStyle(
                  fontSize: 28,
                  fontWeight: FontWeight.w800,
                  color: AppTheme.primary,
                  letterSpacing: -1,
                ),
              ),
              const SizedBox(height: 4),
              const Text(
                'Attendance & HR Suite',
                style: TextStyle(
                  fontSize: 14,
                  color: AppTheme.textSecondary,
                  fontWeight: FontWeight.w500,
                ),
              ),
              const SizedBox(height: 48),
              const SizedBox(
                width: 24,
                height: 24,
                child: CircularProgressIndicator(
                  strokeWidth: 2.5,
                  valueColor: AlwaysStoppedAnimation<Color>(AppTheme.accent),
                ),
              ),
            ],
          ),
        ),
      );
    }

    // Redirect to appropriate screen based on login status
    if (authController.currentUser != null) {
      return const DashboardScreen();
    } else {
      return const LoginScreen();
    }
  }
}
